version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: null
    interval: daily
    time: '00:00'
    timezone: Africa/Cairo
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - '@docusaurus*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
