version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '00:00'
      timezone: Africa/Cairo
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - '@docusaurus*'
          - '@fortawesome*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
