// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Start',
      collapsed: false,
      items: [
        // Journey order for a brand-new user: get oriented, install, run the
        // first test, then see where the evidence and CI hookup live. Upgrade
        // is deliberately NOT here — it is an existing-project task, reparented
        // into Reference below via a sidebar id reference (docs IA #840). Both
        // 'features/reporting' and 'reference/guides/CI_CD_Integration' keep
        // their original files/URLs/categories; they are cross-listed here so
        // "run tests -> read the report -> wire into CI" is a first-class,
        // one-click Start journey instead of being buried behind a collapsed
        // category (issue #842 architecture note).
        'start/overview',
        'start/installation',
        {
          // Diátaxis split (#1079): the overview keeps /docs/start/local-infrastructure.
          type: 'category',
          label: 'Set up local infrastructure',
          link: {type: 'doc', id: 'start/local-infrastructure'},
          items: [
            'start/local-infrastructure/mobile',
            'start/local-infrastructure/services',
            'start/local-infrastructure/previews',
            'start/local-infrastructure/reference',
          ],
        },
        'start/quick-start',
        'features/reporting',
        'reference/guides/CI_CD_Integration',
      ],
    },
    {
      type: 'category',
      label: 'What\'s new',
      collapsed: false,
      items: [
        'features/whats-new/index',
        'features/whats-new/platform',
        'features/whats-new/capture',
        'features/whats-new/agentic',
        'features/whats-new/evidence',
        'features/whats-new/testing',
        'features/whats-new/modules',
        'features/whats-new/missed',
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      collapsed: false,
      items: [
        'testing/web',
        'testing/api',
        'testing/mobile',
        'testing/flutter',
        'testing/database',
        'testing/cli',
        'testing/contracts',
        'testing/flakiness',
      ],
    },
    {
      type: 'category',
      label: 'Agentic',
      collapsed: true,
      items: [
        'agentic/overview',
        'agentic/chaos-engine',
        'agentic/skills',
        'agentic/mcp',
        'agentic/intellij',
        'agentic/cli',
        'agentic/pilot',
        'agentic/capture',
        'agentic/doctor',
        'agentic/heal',
        'agentic/providers',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        'features/architecture',
        'features/test-automation-pillars',
        'features/modules',
        'features/reporting',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'integrations/browserstack',
        'integrations/visual',
        'integrations/ocr',
        'integrations/desktop-and-video',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/overview',
        'reference/reporting',
        {type: 'autogenerated', dirName: 'reference'},
        // Reparented from Start (docs IA #840 / #842): the upgrade tool is a
        // one-time task for an existing project, not part of the new-user
        // path. Sidebar id reference only — the file stays at
        // docs/start/upgrade.mdx with its original /docs/start/upgrade URL
        // (19 external inbound links + a docs-quality singleton rule + a
        // sitemap priority tier all key off that path). Diátaxis split (#1078):
        // the overview keeps that URL; how-to, explanation, and reference pages
        // live under /docs/start/upgrade/*.
        {
          type: 'category',
          label: 'Upgrade to modular SHAFT',
          link: {type: 'doc', id: 'start/upgrade'},
          items: ['start/upgrade/run', 'start/upgrade/how-it-works', 'start/upgrade/reference'],
        },
      ],
    },
  ],
};

module.exports = sidebars;
