// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Journeys',
      collapsed: false,
      link: {type: 'doc', id: 'journeys/index'},
      items: [
        'journeys/create-a-project',
        'journeys/upgrade-a-project',
        'journeys/skills',
        'journeys/intellij',
        'journeys/mcp',
        'journeys/cli',
        'journeys/ci',
        {
          type: 'category',
          label: 'Add a test surface',
          link: {type: 'doc', id: 'journeys/add-a-surface'},
          items: [
            'testing/web',
            'testing/api',
            'testing/mobile',
            'testing/flutter',
            'testing/database',
            'testing/cli',
            'testing/contracts',
          ],
        },
        {
          type: 'category',
          label: 'Install local infrastructure',
          link: {type: 'doc', id: 'start/local-infrastructure'},
          items: [
            'start/local-infrastructure/mobile',
            'start/local-infrastructure/services',
            'start/local-infrastructure/previews',
            'start/local-infrastructure/reference',
          ],
        },
        'agentic/chaos-engine',
        'agentic/chaos-engine-addons',
      ],
    },
    {
      type: 'category',
      label: 'Look up a fact',
      collapsed: true,
      link: {type: 'doc', id: 'reference/overview'},
      items: [
        {type: 'autogenerated', dirName: 'reference'},
        'integrations/browserstack',
        'integrations/visual',
        'integrations/ocr',
        'integrations/desktop-and-video',
        'start/installation',
        'start/quick-start',
        'start/upgrade',
        'start/upgrade/run',
        'start/upgrade/how-it-works',
        'start/upgrade/reference',
        'agentic/skills',
        'agentic/intellij',
        'agentic/mcp',
        'agentic/cli',
        'agentic/capture',
        'agentic/doctor',
        'agentic/heal',
        'agentic/pilot',
        'agentic/providers',
        'features/reporting',
      ],
    },
  ],
};

module.exports = sidebars;
