/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        "Getting_Started/first_steps",
        "Getting_Started/first_steps_2",
        "Getting_Started/first_steps_3",
        "Getting_Started/first_steps_4",
        "Getting_Started/first_steps_5",
        "Getting_Started/first_steps_6",
        {
          type: 'category',
          label: 'Setup by Project Type',
          collapsible: true,
          collapsed: true,
          items: [
            "Getting_Started/setup_web",
            "Getting_Started/setup_web_testng",
            "Getting_Started/setup_web_junit5",
            "Getting_Started/setup_web_cucumber",
            "Getting_Started/setup_mobile",
            "Getting_Started/setup_api",
          ],
        },
        "Getting_Started/integrations",
        "Getting_Started/support",
      ],
    },
    {
      type: 'category',
      label: 'Basic Configuration',
      collapsible: true,
      collapsed: true,
      items: [
        "Basic_Config/basicConfig",
        "Basic_Config/basicConfig2",
        "Basic_Config/basicConfig3",
        "Basic_Config/parallelExecution",
      ],
    },
    {
      type: 'category',
      label: 'Actions',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'GUI',
          items: [
            "Keywords/GUI/Browser_Actions",
            "Keywords/GUI/Element_Identification",
            "Keywords/GUI/Element_Actions",
            "Keywords/GUI/Element_Validations",
            "Keywords/GUI/Touch_Actions",
            {
	    type: 'category',
            label: 'Did You Know',
            collapsible: true,
            collapsed: false,
            items: [
		        "Keywords/GUI/didYouKnow/Native_selenium_Webdriver",
		        "Keywords/GUI/didYouKnow/Custom_Capabilities",
		        "Keywords/GUI/didYouKnow/Local_Selenium_Grid_Execution",
			"Keywords/GUI/didYouKnow/Shaft_Locator_Builder",
		        "Keywords/GUI/didYouKnow/Shadow_Dom_Locator_Builder",
		        "Keywords/GUI/didYouKnow/Integrate_JIRA_With_SHAFT_Engine",
		        "Keywords/GUI/didYouKnow/Using_Cookies_In_Your_Tests",
			]
			}
          ],
        },
        {
          type: 'category',
          label: 'API',
          items: [
            "Keywords/API/Request_Builder",
            "Keywords/API/Response_Getters",
            "Keywords/API/Response_Validations",
          ],
        },
        {
          type: 'category',
          label: 'CLI',
          items: [
            "Keywords/CLI/Terminal_Actions",
            "Keywords/CLI/File_Actions",
          ],
        },
        {
          type: 'category',
          label: 'DB',
          items: [
            "Keywords/DB/DB_Actions",
            "Keywords/DB/Connection_Strings",
            "Keywords/DB/Oracle_JDBC_Setup",
          ],
        },
        "Keywords/TestData_Management",
      ],
    },
    {
      type: 'category',
      label: 'Validations',
      collapsible: true,
      collapsed: true,
      items: [
        "Keywords/Validations/Overview",
        "Keywords/Validations/Browser",
        "Keywords/Validations/Elements",
        "Keywords/Validations/Response",
        "Keywords/Validations/Files",
        "Keywords/Validations/Objects",
        "Keywords/Validations/Nums",
        "Keywords/Validations/ForceFail",
      ],
    },
    {
      type: 'category',
      label: 'Properties',
      collapsible: true,
      collapsed: true,
      items: [
        "Properties/PropertyTypes",
        "Properties/CommonExamples",
        "Properties/PropertiesList",
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      collapsible: true,
      collapsed: true,
      items: [
        "Demos/web",
        "Demos/mobile",
      ],
    },
  ],
};

module.exports = sidebars;