import React, {useMemo, useState} from 'react';
import CodeBlock from '@theme/CodeBlock';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faCheck, faCopy, faDownload, faMagnifyingGlass} from '@fortawesome/free-solid-svg-icons';
import propertiesCatalog from '@site/src/data/properties-catalog.json';
import styles from './styles.module.css';

type PropertyDefinition = {
  section: string;
  key: string;
  targetFile: string;
  defaultValue: string;
  possibleValues: string;
  description: string;
  sensitive?: boolean;
};

const catalog = propertiesCatalog as PropertyDefinition[];
const propertiesDirectory = 'src/main/resources/properties';

function propertyId(property: PropertyDefinition): string {
  return `${property.targetFile}:${property.key}`;
}

function targetPath(targetFile: string): string {
  return `${propertiesDirectory}/${targetFile}`;
}

function sanitizeValue(value: string): string {
  return value.replace(/\r?\n/gu, ' ').trim();
}

function selectOptions(possibleValues: string): string[] {
  if (!possibleValues) return [];
  const options = possibleValues.split(',').map((value) => value.trim()).filter(Boolean);
  if (options.length < 2 || options.length > 12) return [];
  if (options.some((value) => value.length > 36 || /example|host:port|http|range| or /iu.test(value))) return [];
  return options;
}

function buildPropertiesFile(
  targetFile: string,
  selectedProperties: PropertyDefinition[],
  values: Record<string, string>,
): string {
  const lines = [
    '# Generated by SHAFT custom properties generator',
    `# Place this file at: ${targetPath(targetFile)}`,
  ];
  let currentSection = '';

  for (const property of selectedProperties.filter((item) => item.targetFile === targetFile)) {
    if (currentSection !== property.section) {
      currentSection = property.section;
      lines.push('', `# ${currentSection}`);
    }
    lines.push(`${property.key}=${sanitizeValue(values[propertyId(property)] ?? property.defaultValue)}`);
  }

  return `${lines.join('\n')}\n`;
}

export function PropertiesGenerator(): JSX.Element {
  const [query, setQuery] = useState('');
  const [section, setSection] = useState('all');
  const [targetFile, setTargetFile] = useState('all');
  const [selectedOnly, setSelectedOnly] = useState(false);
  const [selected, setSelected] = useState<Record<string, boolean>>({});
  const [values, setValues] = useState<Record<string, string>>(
    () => Object.fromEntries(catalog.map((property) => [propertyId(property), property.defaultValue])),
  );
  const [status, setStatus] = useState('');

  const sections = useMemo(() => Array.from(new Set(catalog.map((property) => property.section))), []);
  const targetFiles = useMemo(() => Array.from(new Set(catalog.map((property) => property.targetFile))), []);

  const filteredProperties = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return catalog.filter((property) => {
      const id = propertyId(property);
      if (section !== 'all' && property.section !== section) return false;
      if (targetFile !== 'all' && property.targetFile !== targetFile) return false;
      if (selectedOnly && !selected[id]) return false;
      if (!normalizedQuery) return true;
      return [
        property.key,
        property.section,
        property.targetFile,
        property.description,
        property.possibleValues,
      ].some((value) => value.toLowerCase().includes(normalizedQuery));
    });
  }, [query, section, selected, selectedOnly, targetFile]);

  const groupedProperties = useMemo(() => {
    const groups = new Map<string, PropertyDefinition[]>();
    for (const property of filteredProperties) {
      groups.set(property.section, [...(groups.get(property.section) ?? []), property]);
    }
    return Array.from(groups.entries());
  }, [filteredProperties]);

  const selectedProperties = useMemo(
    () => catalog.filter((property) => selected[propertyId(property)]),
    [selected],
  );

  const generatedFiles = useMemo(
    () => targetFiles
      .map((fileName) => ({
        fileName,
        content: buildPropertiesFile(fileName, selectedProperties, values),
        count: selectedProperties.filter((property) => property.targetFile === fileName).length,
      }))
      .filter((file) => file.count > 0),
    [selectedProperties, targetFiles, values],
  );

  function updateValue(property: PropertyDefinition, value: string): void {
    setValues((current) => ({...current, [propertyId(property)]: value}));
  }

  function toggleProperty(property: PropertyDefinition): void {
    const id = propertyId(property);
    setSelected((current) => ({...current, [id]: !current[id]}));
  }

  async function downloadAndCopy(fileName: string, content: string): Promise<void> {
    const blob = new Blob([content], {type: 'text/plain;charset=utf-8'});
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    link.click();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);

    try {
      await navigator.clipboard.writeText(content);
      setStatus(`${fileName} downloaded and copied.`);
    } catch {
      setStatus(`${fileName} downloaded. Clipboard copy was blocked by the browser.`);
    }
  }

  return (
    <div className={styles.root}>
      <section className={styles.destination} aria-label="Generated file destination">
        <strong>Place generated files here:</strong>
        <code>{propertiesDirectory}/</code>
        <span>SHAFT reads every <code>.properties</code> file in this folder.</span>
      </section>

      <div className={styles.toolbar}>
        <label className={styles.searchBox}>
          <span><FontAwesomeIcon icon={faMagnifyingGlass} /> Search</span>
          <input
            type="search"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Property name, section, or description"
          />
        </label>

        <label>
          <span>Section</span>
          <select value={section} onChange={(event) => setSection(event.target.value)}>
            <option value="all">All sections</option>
            {sections.map((name) => <option key={name} value={name}>{name}</option>)}
          </select>
        </label>

        <label>
          <span>File</span>
          <select value={targetFile} onChange={(event) => setTargetFile(event.target.value)}>
            <option value="all">All files</option>
            {targetFiles.map((fileName) => <option key={fileName} value={fileName}>{fileName}</option>)}
          </select>
        </label>

        <label className={styles.selectedOnly}>
          <input
            type="checkbox"
            checked={selectedOnly}
            onChange={(event) => setSelectedOnly(event.target.checked)}
          />
          <span>Selected only</span>
        </label>
      </div>

      <div className={styles.summary} aria-live="polite">
        <span>{filteredProperties.length} properties shown</span>
        <span>{selectedProperties.length} selected</span>
      </div>

      <div className={styles.layout}>
        <section className={styles.catalogPanel} aria-label="Available SHAFT properties">
          {groupedProperties.map(([groupName, properties]) => (
            <section className={styles.group} key={groupName}>
              <h2>{groupName}</h2>
              {properties.map((property) => {
                const id = propertyId(property);
                const options = selectOptions(property.possibleValues);
                return (
                  <article className={styles.propertyRow} data-property-key={property.key} data-target-file={property.targetFile} key={id}>
                    <div className={styles.propertyHeader}>
                      <label className={styles.propertyChoice}>
                        <input
                          type="checkbox"
                          checked={Boolean(selected[id])}
                          onChange={() => toggleProperty(property)}
                        />
                        <span>
                          <strong>{property.key}</strong>
                          <small>{targetPath(property.targetFile)}</small>
                        </span>
                      </label>
                    </div>

                    <p>{property.description}</p>

                    <dl className={styles.metadata}>
                      <div>
                        <dt>Default</dt>
                        <dd><code>{property.sensitive ? 'blank' : property.defaultValue || 'blank'}</code></dd>
                      </div>
                      <div>
                        <dt>Possible values</dt>
                        <dd>{property.possibleValues || 'Any valid value'}</dd>
                      </div>
                    </dl>

                    <label className={styles.valueField}>
                      <span>Value</span>
                      {options.length > 0 ? (
                        <select value={values[id] ?? property.defaultValue} onChange={(event) => updateValue(property, event.target.value)}>
                          {options.map((option) => <option key={option} value={option}>{option}</option>)}
                        </select>
                      ) : (
                        <input
                          type={property.sensitive ? 'password' : 'text'}
                          value={values[id] ?? property.defaultValue}
                          onChange={(event) => updateValue(property, event.target.value)}
                          placeholder={property.sensitive ? 'Enter value locally' : property.defaultValue}
                        />
                      )}
                    </label>
                  </article>
                );
              })}
            </section>
          ))}
        </section>

        <aside className={styles.outputPanel} aria-label="Generated properties files">
          <div className={styles.outputHeader}>
            <h2>Generated files</h2>
            {status ? <span className={styles.status}><FontAwesomeIcon icon={faCheck} /> {status}</span> : null}
          </div>

          {generatedFiles.length === 0 ? (
            <p className={styles.empty}>Select one or more properties to generate files.</p>
          ) : generatedFiles.map((file) => (
            <section className={styles.generatedFile} key={file.fileName}>
              <div className={styles.fileActions}>
                <div>
                  <strong>{file.fileName}</strong>
                  <small>{targetPath(file.fileName)}</small>
                </div>
                <button
                  type="button"
                  onClick={() => void downloadAndCopy(file.fileName, file.content)}
                  aria-label={`Download and copy ${file.fileName}`}
                >
                  <FontAwesomeIcon icon={faDownload} />
                  <FontAwesomeIcon icon={faCopy} />
                  <span>Download + Copy</span>
                </button>
              </div>
              <CodeBlock language="properties">{file.content}</CodeBlock>
            </section>
          ))}
        </aside>
      </div>
    </div>
  );
}
