import React, {useMemo, useState} from 'react';
import CodeBlock from '@theme/CodeBlock';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faCheck, faCopy, faDownload, faPlus, faXmark, faMagnifyingGlass, faBroom} from '@fortawesome/free-solid-svg-icons';
import propertiesCatalog from '@site/src/data/properties-catalog.json';
import styles from './styles.module.css';

type PropertyType = 'boolean' | 'text' | 'number';

type PropertyDefinition = {
  section: string;
  key: string;
  targetFile: string;
  type: PropertyType;
  defaultValue: string;
  possibleValues: string;
  description: string;
  sensitive?: boolean;
};

const catalog = propertiesCatalog as PropertyDefinition[];
const propertiesDirectory = 'src/main/resources/properties';
const ALL_SECTIONS = 'all';

function targetPath(targetFile: string): string {
  return `${propertiesDirectory}/${targetFile}`;
}

function sanitizeValue(value: string): string {
  return value.replace(/\r?\n/gu, ' ').trim();
}

/**
 * Decides whether `possibleValues` is a clean, renderable enum. Guards, in order: not comma-shaped
 * at all; too many/too long options to be a real enum; option text that reads as prose rather than
 * a literal value (an "example:"/URL/host:port hint, a numeric range such as "0-100", or a
 * natural-language list tail such as "or a ServiceLoader planner ID").
 */
function selectOptions(possibleValues: string): string[] {
  if (!possibleValues) return [];
  const options = possibleValues.split(',').map((value) => value.trim()).filter(Boolean);
  if (options.length < 2 || options.length > 12) return [];
  const looksLikeRange = (value: string) => /^-?\d+(\.\d+)?\s*(-|to|–|—)\s*-?\d+(\.\d+)?$/iu.test(value);
  const looksLikeProseTail = (value: string) => /^(or|and)\s/iu.test(value) || value.split(/\s+/u).length > 4;
  if (options.some((value) => value.length > 36
    || looksLikeRange(value)
    || looksLikeProseTail(value)
    || /example|host:port|http|:\/\//iu.test(value))) return [];
  return options;
}

function buildPropertiesFile(
  targetFile: string,
  selectedProperties: PropertyDefinition[],
  values: Record<string, string>,
): string {
  const lines = [
    '# Generated by the SHAFT custom properties generator',
    `# Place this file at: ${targetPath(targetFile)}`,
  ];
  let currentSection = '';

  for (const property of selectedProperties.filter((item) => item.targetFile === targetFile)) {
    if (currentSection !== property.section) {
      currentSection = property.section;
      lines.push('', `# ${currentSection}`);
    }
    lines.push(`${property.key}=${sanitizeValue(values[property.key] ?? property.defaultValue)}`);
  }

  return `${lines.join('\n')}\n`;
}

export function PropertiesGenerator(): JSX.Element {
  const [query, setQuery] = useState('');
  const [section, setSection] = useState(ALL_SECTIONS);
  const [selectedOnly, setSelectedOnly] = useState(false);
  const [selected, setSelected] = useState<Record<string, boolean>>({});
  const [values, setValues] = useState<Record<string, string>>({});
  const [status, setStatus] = useState('');

  const sections = useMemo(() => Array.from(new Set(catalog.map((property) => property.section))), []);
  const targetFiles = useMemo(() => Array.from(new Set(catalog.map((property) => property.targetFile))), []);

  const normalizedQuery = query.trim().toLowerCase();
  const matchesQuery = (property: PropertyDefinition) => {
    if (!normalizedQuery) return true;
    return [property.key, property.section, property.targetFile, property.description, property.possibleValues]
      .some((value) => value.toLowerCase().includes(normalizedQuery));
  };

  // Per-section counts against the current search only (not the section filter itself), so the
  // category rail narrows live as you type and you can see which sections still have matches.
  const sectionCounts = useMemo(() => {
    const counts = new Map<string, number>();
    for (const property of catalog) {
      if (!matchesQuery(property)) continue;
      counts.set(property.section, (counts.get(property.section) ?? 0) + 1);
    }
    return counts;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [normalizedQuery]);

  const filteredProperties = useMemo(() => catalog.filter((property) => {
    if (section !== ALL_SECTIONS && property.section !== section) return false;
    if (selectedOnly && !selected[property.key]) return false;
    return matchesQuery(property);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }), [normalizedQuery, section, selected, selectedOnly]);

  const groupedProperties = useMemo(() => {
    const groups = new Map<string, PropertyDefinition[]>();
    for (const property of filteredProperties) {
      groups.set(property.section, [...(groups.get(property.section) ?? []), property]);
    }
    return Array.from(groups.entries());
  }, [filteredProperties]);

  const selectedProperties = useMemo(
    () => catalog.filter((property) => selected[property.key]),
    [selected],
  );

  const generatedFiles = useMemo(
    () => targetFiles
      .map((fileName) => ({
        fileName,
        content: buildPropertiesFile(fileName, selectedProperties, values),
        count: selectedProperties.filter((property) => property.targetFile === fileName).length,
      }))
      .filter((file) => file.count > 0),
    [selectedProperties, targetFiles, values],
  );

  function updateValue(property: PropertyDefinition, value: string): void {
    setValues((current) => ({...current, [property.key]: value}));
  }

  function addProperty(property: PropertyDefinition): void {
    setSelected((current) => ({...current, [property.key]: true}));
  }

  function removeProperty(property: PropertyDefinition): void {
    setSelected((current) => {
      const next = {...current};
      delete next[property.key];
      return next;
    });
  }

  function clearSelection(): void {
    setSelected({});
    setValues({});
    setStatus('');
  }

  async function copyFile(fileName: string, content: string): Promise<void> {
    try {
      await navigator.clipboard.writeText(content);
      setStatus(`${fileName} copied to clipboard.`);
    } catch {
      setStatus(`Could not copy ${fileName} — your browser blocked clipboard access.`);
    }
  }

  function downloadFile(fileName: string, content: string): void {
    const blob = new Blob([content], {type: 'text/plain;charset=utf-8'});
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    link.click();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
    setStatus(`${fileName} downloaded.`);
  }

  return (
    <div className={styles.root}>
      <section className={styles.destination} aria-label="Generated file destination">
        <strong>Place generated files here:</strong>
        <code>{propertiesDirectory}/</code>
        <span>SHAFT reads every <code>.properties</code> file in this folder.</span>
      </section>

      <div className={styles.toolbar}>
        <label className={styles.searchBox}>
          <span><FontAwesomeIcon icon={faMagnifyingGlass} /> Search {catalog.length} properties</span>
          <input
            type="search"
            autoFocus
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Property name, section, or description"
          />
        </label>

        <label className={styles.selectedOnly}>
          <input
            type="checkbox"
            checked={selectedOnly}
            onChange={(event) => setSelectedOnly(event.target.checked)}
          />
          <span>Selected only</span>
        </label>
      </div>

      <div className={styles.summary} aria-live="polite">
        <span>{filteredProperties.length} of {catalog.length} properties shown</span>
        <span>{selectedProperties.length} selected</span>
        {selectedProperties.length > 0 && (
          <button type="button" className={styles.clearButton} onClick={clearSelection}>
            <FontAwesomeIcon icon={faBroom} /> Clear selection
          </button>
        )}
      </div>

      <div className={styles.layout}>
        <nav className={styles.categoryRail} aria-label="Property categories">
          <button
            type="button"
            className={section === ALL_SECTIONS ? styles.categoryActive : styles.category}
            onClick={() => setSection(ALL_SECTIONS)}
          >
            All categories <span>{catalog.filter(matchesQuery).length}</span>
          </button>
          {sections.map((name) => (
            <button
              type="button"
              key={name}
              className={section === name ? styles.categoryActive : styles.category}
              onClick={() => setSection(name)}
              disabled={(sectionCounts.get(name) ?? 0) === 0 && normalizedQuery !== ''}
            >
              {name} <span>{sectionCounts.get(name) ?? 0}</span>
            </button>
          ))}
        </nav>

        <section className={styles.catalogPanel} aria-label="Available SHAFT properties">
          {groupedProperties.length === 0 && (
            <p className={styles.empty}>No properties match this search.</p>
          )}
          {groupedProperties.map(([groupName, properties]) => (
            <section className={styles.group} key={groupName}>
              <h2>{groupName}</h2>
              {properties.map((property) => {
                const isSelected = Boolean(selected[property.key]);
                const options = selectOptions(property.possibleValues);
                const defaultBadge = property.sensitive ? 'blank' : (property.defaultValue || 'blank');

                if (!isSelected) {
                  return (
                    <button
                      type="button"
                      className={styles.propertyRow}
                      data-property-key={property.key}
                      key={property.key}
                      onClick={() => addProperty(property)}
                    >
                      <span className={styles.propertyMain}>
                        <strong>{property.key}</strong>
                        <small>{property.description}</small>
                      </span>
                      <span className={styles.propertyAside}>
                        <code className={styles.defaultBadge}>{defaultBadge}</code>
                        <span className={styles.addIcon} aria-hidden="true"><FontAwesomeIcon icon={faPlus} /></span>
                      </span>
                    </button>
                  );
                }

                return (
                  <article className={styles.propertyRowSelected} data-property-key={property.key} key={property.key}>
                    <div className={styles.propertyHeader}>
                      <span>
                        <strong>{property.key}</strong>
                        <small>{targetPath(property.targetFile)}</small>
                      </span>
                      <button
                        type="button"
                        className={styles.removeButton}
                        aria-label={`Remove ${property.key}`}
                        onClick={() => removeProperty(property)}
                      >
                        <FontAwesomeIcon icon={faXmark} />
                      </button>
                    </div>

                    <p>{property.description}</p>

                    <label className={styles.valueField}>
                      <span>Value {property.possibleValues && options.length === 0 ? `(${property.possibleValues})` : ''}</span>
                      {options.length > 0 ? (
                        <select value={values[property.key] ?? property.defaultValue} onChange={(event) => updateValue(property, event.target.value)}>
                          {options.map((option) => <option key={option} value={option}>{option}</option>)}
                        </select>
                      ) : (
                        <input
                          type={property.sensitive ? 'password' : property.type === 'number' ? 'number' : 'text'}
                          step={property.type === 'number' ? 'any' : undefined}
                          value={values[property.key] ?? property.defaultValue}
                          onChange={(event) => updateValue(property, event.target.value)}
                          placeholder={property.sensitive ? 'Enter value locally' : property.defaultValue}
                        />
                      )}
                    </label>
                  </article>
                );
              })}
            </section>
          ))}
        </section>

        <aside className={styles.outputPanel} aria-label="Generated properties files">
          <div className={styles.outputHeader}>
            <h2>Generated files</h2>
            {status ? <span className={styles.status}><FontAwesomeIcon icon={faCheck} /> {status}</span> : null}
          </div>

          {generatedFiles.length === 0 ? (
            <p className={styles.empty}>Select one or more properties to generate files.</p>
          ) : generatedFiles.map((file) => (
            <section className={styles.generatedFile} key={file.fileName}>
              <div className={styles.fileActions}>
                <div>
                  <strong>{file.fileName}</strong>
                  <small>{targetPath(file.fileName)}</small>
                </div>
                <div className={styles.fileButtons}>
                  <button type="button" onClick={() => void copyFile(file.fileName, file.content)}>
                    <FontAwesomeIcon icon={faCopy} /> Copy
                  </button>
                  <button type="button" onClick={() => downloadFile(file.fileName, file.content)}>
                    <FontAwesomeIcon icon={faDownload} /> Download
                  </button>
                </div>
              </div>
              <CodeBlock language="properties">{file.content}</CodeBlock>
            </section>
          ))}
        </aside>
      </div>
    </div>
  );
}
